In [2]:
import numpy as np


print("\n# ===== 1. 创建数组 =====")
arr1 = np.array([1,2,3])
print("arr1:",arr1)
arr2 = np.zeros((2,3))
print("全零数组：\n",arr2)

arr3 = np.arange(0,10,3)
print("等差数组：",arr3)

arr4 = np.ones((3,3))
print("全1数组：\n",arr4)

arr5 = np.linspace(0,1,5)
print("等间距数组：\n",arr5)


print("\n# ===== 2. 数组属性 =====")
print("arr1 shape",arr1.shape)
print("arr2 dtype:",arr2.dtype)
print("arr4 ndim:",arr4.ndim) # 维度数

print("\n# ===== 3. 数组切片 & 索引 =====")
mat = np.arange(1,13).reshape(3,4)
print("mat:\n",mat)
print("第一行：",mat[0])
print("第一列:",mat[:,0])
print("前两行，前两列：",mat[:2,:2])
print("大于5的元素：",mat[mat>5])
print("高级索引：",mat[[0,2],[1,3]]) # 定位 mat[0,1] 和 mat[2,3]


# ===== 1. 创建数组 =====
arr1: [1 2 3]
全零数组：
 [[0. 0. 0.]
 [0. 0. 0.]]
等差数组： [0 3 6 9]
全1数组：
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
等间距数组：
 [0.   0.25 0.5  0.75 1.  ]

# ===== 2. 数组属性 =====
arr1 shape (3,)
arr2 dtype: float64
arr4 ndim: 2

# ===== 3. 数组切片 & 索引 =====
mat:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
第一行： [1 2 3 4]
第一列: [1 5 9]
前两行，前两列： [[1 2]
 [5 6]]
大于5的元素： [ 6  7  8  9 10 11 12]
高级索引： [ 2 12]


In [43]:
print("\n# ===== 4. 数组运算 & 广播 =====")
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a+b:",a+b)
print("a*2:",a*2)

# 广播示例 (列向量 + 行向量)
x = np.array([[1],[2],[3]])
y = np.array([10,20,30])
print("广播相加：\n",x+y)


# ===== 4. 数组运算 & 广播 =====
a+b: [5 7 9]
a*2: [2 4 6]
广播相加：
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [46]:
print("\n# ===== 5. 常用数学函数 =====")
print("mat:" ,mat)
print("sum:",np.sum(mat))
print("mean:", np.mean(mat))
print("max:", np.max(mat))
print("min:", np.min(mat))
print("std:", np.std(mat))
print("argmax index:", np.argmax(mat))


# ===== 5. 常用数学函数 =====
mat: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sum: 78
mean: 6.5
max: 12
min: 1
std: 3.452052529534663
argmax index: 11


In [5]:
# 练习：生成一个 5x5 随机矩阵，计算它的每列平均值
print("\n# 练习：5x5随机矩阵的列平均值")
rand_mat = np.random.randint(1,10,size=(5,5))
print("rand_mat:",rand_mat)
print("列平均值：",np.mean(rand_mat,axis=0))


# 练习：5x5随机矩阵的列平均值
rand_mat: [[6 1 5 3 9]
 [5 3 2 5 3]
 [4 7 7 7 1]
 [2 5 4 9 2]
 [7 9 6 8 9]]
列平均值： [4.8 5.  4.8 6.4 4.8]


In [55]:
np.arange(10,50,5)
a = np.arange(0,16).reshape(4,4)
print("a:\n",a)
print(a[1:3,0:2])

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[4 5]
 [8 9]]


In [58]:
new_mat = np.random.randint(2,9,size=(3,3))
print("new_mat:\n",new_mat)
print(np.max(new_mat))
print(np.min(new_mat))
print(np.sum(new_mat))
print(np.average(new_mat))
print(np.mean(new_mat))

new_mat:
 [[8 5 6]
 [2 4 2]
 [4 2 5]]
8
2
38
4.222222222222222
4.222222222222222


In [ ]:
mat_0 = np.arange(1,20)
print(mat_0)
mat_0 = [x**2 for x in mat_0 if x%2==0]
print(mat_0)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[np.int64(4), np.int64(16), np.int64(36), np.int64(64), np.int64(100), np.int64(144), np.int64(196), np.int64(256), np.int64(324)]
